### ISSUE TITLE
Автодокументация для ember-flexberry и ember-flexberry-data

### ISSUE THREAD

**Issue by KollegOFF** [Flexberry/flexberry.github.io#28]
- [x] Настроить генерацию и публикацию для [Flexberry/ember-flexberry](https://github.com/Flexberry/ember-flexberry) [#757](https://github.com/Flexberry/ember-flexberry/pull/757)
- [x] Настроить генерацию и публикацию для [Flexberry/ember-flexberry-data](https://github.com/Flexberry/ember-flexberry-data) [#121](https://github.com/Flexberry/ember-flexberry-data/pull/121)
- [x] Добавить ссылки в раздел `Flexberry Ember » Справочники по API` #32
