### ISSUE TITLE
Автодокументация для NewPlatform.Flexberry.ORM и NewPlatform.Flexberry.ORM.ODataService

### ISSUE THREAD

**Issue by KollegOFF** [Flexberry/flexberry.github.io#29]
- [x] Настроить генерацию и публикацию для [Flexberry/NewPlatform.Flexberry.ORM](https://github.com/Flexberry/NewPlatform.Flexberry.ORM) [#41](https://github.com/Flexberry/NewPlatform.Flexberry.ORM/pull/41)
- [x] Настроить генерацию и публикацию для [Flexberry/NewPlatform.Flexberry.ORM.ODataService](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService) [#17](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/pull/17)
- [x] Добавить ссылки в раздел `Flexberry ORM » Справочники по API` #35
